### ISSUE TITLE
FinRL_single_stock_trading.ipynb - unexpected parameter trade_data for  DRL_prediction() function

### ISSUE THREAD

**Issue by enomis-31** [AI4Finance-LLC/FinRL-Library#89] opened 2021-01-27 23:35 UTC
Hi all, 

First of all I would like to thank you for the fantastic work you have done.
The library is well done, complete and the documentation including tutorials and scientific papers is a really good job.

I am writing because I find a problem in the reproduction of the Notebook in question (Single stock), it seems that the parameters used are not defined in the function present in the source code.

This is the error:
TypeError: DRL_prediction() got an unexpected keyword argument 'trade_data'

Can you fix it please?

SM

**Comment by XiaoYangLiu-FinRL** [comment] 2021-01-29 23:56
Could you please test the multiple stock case?   We updated and merged single stock to it.  Thx for any feeback.

**Comment by enomis-31** [comment] 2021-01-30 00:25
I have checked, it seems the code has the same problem. 

I check in the model.py, arguments test_data, test_env and test_obs arent defined as parameters. I solved giving to the  DRL_predicition function in the notebook only (model=,environment=) parameter. 

I check also in the backtest.py file and I ve seen that you define functions with different names from the function called in the notebook:
backtest_stats
backtest_plot 
Moreover there aren't functions such as baseline_stats. 

However, I would say again, great job.
Thanks

**Comment by setar** [comment] 2021-01-31 00:00
try add ', get_baseline'
"from finrl.trade.backtest import backtest_stats, backtest_plot, get_daily_return, get_baseline"
it work for me

**Comment by spencerR1992** [comment] 2021-01-31 15:58
Hi, I believe a recent push resolved this issue. Can you please pull and try again? I am closing this issue and if you encounter more issues, please open another issue!

**Closed by spencerR1992** 2021-01-31 15:58 UTC

**Comment by jvukoja** [comment] 2021-02-07 17:36
For me the problem is still here. I just cloned the repo and I guess I used the latest code.

![image](https://user-images.githubusercontent.com/64794170/107154435-3538c300-6973-11eb-9dbe-d26161be269b.png)

**Comment by ErikBaer** [comment] 2021-03-24 13:46
Hello everybody,

first of all let me congratulate you to your amazing work, as well as thank you for your on-going contribution and the open-source nature of your research. 

When trying to run the notebook FinRL_single_stock_trading, I encountered a similar error as outlined above, with the arguments given in the notebook seemingly not matching the required arguments on models.py.
On futher inspection, it appears that some notebooks call DRL_prediction with different args than others entirely, might that be in fact the case?

Therefore my humble inquiry: Is there an entry point, or respectively a suggestion for the most current reference notebook from where to best start my exploration? Or might there be any suggested changes / adaptations to be implemented locally in order to achieve full functionality?

Kindly thanks a lot for your efforts and for your response,
looking very much forward to contributing to this exciting approach in the future :)

**Comment by RomanZWang** [comment] 2021-06-06 20:41
I'm also looking for confirmation of what the latest intended parameters/argument are.
